### PR TITLE
Add Cirrus CI config for FreeBSD build

### PR DESCRIPTION
**Pull request by lwhsu**
Sponsored by:   The FreeBSD Foundation

### CODE REVIEW

**Comment by asomers** [comment]
travis-build.sh references a "travis" user.  That probably won't exist in Cirrus's images.  We should probably change it to "nobody".

**Comment by lwhsu** [comment]
Hmm, I didn't notice that, btw, the build on cirrus-ci pass: https://cirrus-ci.com/task/6709240718950400

**Comment by asomers** [comment]
Maybe none of Kyua's own tests require an unprivileged user?  It wouldn't surprise me.

**Comment by asomers** [comment]
The PR looks good to me, but I don't have enough privileges to enable the Cirrus-CI app for this repository, and we need to do that before merging.  @bsdjhb could you please enable it according to the instructions at https://cirrus-ci.org/guide/quick-start/ ?  Stop when you get to "post-installation".

**Review by cemeyer — COMMENTED** [review]
I would suggest squashing the two commits together and re-pushing (force push) your PR branch, as the second commit is a trivial fixup for the first.  Otherwise, looks good to me.  Edit: I don't believe we need to wait for the Core team to install Cirrus for this repository before merging this change; it just won't have any effect until then.

**Comment by bsdjhb** [comment]
I've enabled Cirrus for this repository.  If there are other settings (e.g. protecting branches to prevent force pushes or changing the types of commits you can use when closing a PR) that you aren't able to set, let me know.

**Comment by asomers** [comment]
Thanks John.

**Review by asomers — APPROVED** [review]

**Comment by cemeyer** [comment]
> I've enabled Cirrus for this repository. If there are other settings (e.g. protecting branches to prevent force pushes or changing the types of commits you can use when closing a PR) that you aren't able to set, let me know.

@bsdjhb Would you mind enabling it for all the other repositories currently in FreeBSD/ as well?  We don't have .cirrus configs for all of them but it is plausible we might want to in the future, and having it enabled-but-unused seems harmless to me.  If there is a good reason not to, that's fine.  If you've already done so and I just didn't realize, great!

**Comment by bsdjhb** [comment]
I'm a bit hesitant to enable it for all.  We have several clones of upstream repositories (like openjdk, etc.) and we probably don't want to turn on an "inherited" cirrus config from something we clone.  It's pretty easy to turn it in for other repos though and I don't mind doing that.

**Comment by cemeyer** [comment]
LGTM, thanks.

**Pull request merged**
