### PR TITLE
kyua report-html: escape rendered stdout/sterr

### PR DESCRIPTION
**Pull request by tuexen**

### CODE REVIEW

**Review by ngie-eign — COMMENTED** [review]
Looks great to me!! Could you please add some tests and investigate the CI failures?

**Comment by tuexen** [comment]
> Looks great to me!! Could you please add some tests and investigate the CI failures?

Not sure about the tests. Need to figure out how that works. I just worked with @ocochard on getting a TCP testsuite up and running and have not much experience with writing test cases within kyua...

Regarding the CI failure:
```
Standard error:
ld-elf.so.1: Shared object "libncurses.so.9" not found, required by "libedit.so.0"
Fail: incorrect exit status: 1, expected: 0
```
I think this is not related to my patch but to the setup of the CI system running 13.0-STABLE. I don't really know what to do to fix that...

**Comment by kevans91** [comment]
CI result is bogus for now because it was fixed after releng/13.0 branched and we don't produce new stable/13 snapshots until afterward. It succeeded on releng/13.0 and 12.x, chance of failing on stable/13 is pretty low.

**Comment by ngie-eign** [comment]
@tuexen : could you please rebase this change so Cirrus CI reruns the tests?

**Comment by ngie-eign** [comment]
Actually... nevermind--this is fairly straightforward. I'll add tests and CC you on that PR.

**Pull request merged**
