### PR TITLE
Fix regex that breaks integration/cmd_report_test:verbose

### PR DESCRIPTION
**Pull request by vangyzen**

### CODE REVIEW

**Comment by asomers** [comment]
What exactly is the problem, and how does one reproduce it?

**Comment by ngie-eign** [comment]
@asomers : we need to nuke the 11.4/12.2 configs from the cirrus CI yml file: they're not supported anymore.

**Comment by ngie-eign** [comment]
Also, we probably should nuke the 12.2-STABLE one and replace it with 12.3-RELEASE, and replace 13.0-STABLE with 13.1-RELEASE.

**Comment by asomers** [comment]
See #8 for the CI images fix.

**Comment by vangyzen** [comment]
```
$ env 'FOO="198810"' kyua test cmd_report_test:verbose
cmd_report_test:verbose  ->  failed: atf-check failed; see the output of the test for details  [0.035s]
```

**Review by asomers — APPROVED** [review]

**Comment by ngie-eign** [comment]
> $ env 'FOO="198810"' kyua test cmd_report_test:verbose
> cmd_report_test:verbose  ->  failed: atf-check failed; see the output of the test for details  [0.035s]

Awesome! Could you please rebase the PR?

**Comment by ngie-eign** [comment]
Oh, and if you could please add the failing example to the commit message and add a "Sponsored by: <blah blah>" (assuming this was done on $work time), then the change would be good to go!

**Pull request merged**
