### PR TITLE
executor: more gracefully handle buggy tests and PID reuse

### PR DESCRIPTION
**Pull request by vangyzen**
Read executor_pid_test.cpp for the scenario.

Sponsored by:	Dell Inc.

### CODE REVIEW

**Comment by vangyzen** [comment]
- [x] Add a final test case to clear the uunlink flags and actually clean up.  My bad.

**Comment by vangyzen** [comment]
The FreeBSD Test Suite passes with this change (on OneFS).

**Comment by ngie-eign** [comment]
I think this is a good case for the direction @jmmv was trying to go in a few years back by making kyua not automatically clean up sandboxes and instead assert on “turds” (as he called it) being left behind by tests.

**Comment by vangyzen** [comment]
I'd love to have an option to leave the sandbox intact for all non-passing tests.  Maybe it would be a CLI option like `kyua test --no-clean=mumble`.  That would be very useful for intermittent failures.

**Comment by ngie-eign** [comment]
@vangyzen : could you please rebase this PR to pick up the latest Cirrus CI definition?

**Review by ngie-eign — APPROVED** [review]
Thanks @vangyzen !

**Pull request merged**
